Create a basic insticator adaptor
Insticator/prebid-server pull request #3
Opened 2024-05-16 09:07 UTC by shubhamc-ins

2024-06-27 13:26 UTC, rohanInsticator requested changes
1. The latest PrebidJS change of publisherId is not there.
2. I don't see any code related to Content Object.
3. IP & UA logic we discussed is still missing.
4. I don't see any logic related to setting our UserId
5. If a publisher is trying to pass us device or geo objects, they are also not here.

2024-07-03 11:16 UTC, shubhamc-ins commented
Here is initial request payload from postman:
```
{
    "ext": {
        "prebid": {
            "debug": true
        },
        "insticator": {
            "adapter": {
                "vendor": "prebid",
                "prebid": "8.38.0"
            }
        }
    },
    "test": 1,
    "site": {
        "ref": "",
        "domain": "cheeseheadtv.com",
        "page": "https://cheeseheadtv.com/v2.1.147/lol/in-game",
        "keywords": "helo,hry",
        "content": {
            "cat": ["IAB1-1"],
            "genre": "hello"
        },
        "mobile": 1
    },
    "tmax": 7000,
    "regs": {
        "ext": {
            "gdpr": 1        
        }
    },
    "id": "143166a46498cf89",
    "source": {
        "fd": 1
    },
    "device": {
        "sua": {
            "source": 1,
            "platform": {
                "brand": "macOS"
            },
            "browsers": [
                {
                    "brand": "Google Chrome",
                    "version": [
                        "123"
                    ]
                },
                {
                    "brand": "Not:A-Brand",
                    "version": [
                        "8"
                    ]
                },
                {
                    "brand": "Chromium",
                    "version": [
                        "123"
                    ]
                }
            ],
            "mobile": 0
            },
        "ext": {},
        "os": "Windows",
        "h": 1080,
        "ppi": 45,
        "language": "ja",
        "dnt": 0,
        "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.5845.190 Safari/537.36",
        "devicetype": 2,
        "carrier": "So-net",
        "osv": "10",
        "w": 1920,
        "model": "Chrome",
        "connectiontype": 0,
        "make": "Google"
        // "geo": {
        //     "country": "FR"
        // }
    },
    "user": {
        "ext": {
            "eids": [
                {
                    "uids": [
                        {
                            "ext": {
                                "linktype": "2",
                                "pba": "4Gmzuev8uOCkWlYYGEz/7w=="
                            },
                            "atype": 1,
                            "id": "ID5*HE49hy4-v4Pgoe3QSmegEWz6CZV5_v7h_wv1LdRmVT6OF_Vwj1Y5n-gNCHSerhMN"
                        }
                    ],
                    "source": "id5-sync.com"
                },
                {
                    "uids": [
                        {
                            "atype": 1,
                            "id": "0609ljdllbbgihjh7k7g977h6b9akea9gd760wk00ggqusws2y2q622s0g6eyme6q"
                        }
                    ],
                    "source": "audigent.com"
                },
                {
                    "uids": [
                        {
                            "atype": 1,
                            "id": "3fe32eea-612f-41e5-ab35-c85b453cfa7e"
                        }
                    ],
                    "source": "pubcid.org"
                }
            ],
            "consent": "asdasdasd"
        },
        "id": "fc1845bb-c4f1-4064-98b2-7a0aa7acdf20",
        "keywords": "action,sci-fi"
    },
    "imp": [
        {
            "ext": {
                "gpid": "bostonhockeynow.com-div-insticator-ad-1",
                "insticator": {
                    "adUnitId": "01FJF77PSSJ9RTD1RFTYRMV6FG"
                    // "adUnitId": "01EX2DK7MW4BNN8TS2R0AT576D"
                },
                "prebid": {
                    "debug": true,
                    "bidder": {
                        "insticator": {
                            "adUnitId": "01EX2DK7MW4BNN8TS2R0AT576D"
                        }
                    }
                }
            },
            "tagid": "div-insticator-ad-1",
            "banner": {
                "format": [
                    {
                        "w": 300,
                        "h": 250
                    }
                ]
            },
            "id": "8068037539d483f7",
            "secure": 1,
            "bidfloor": 0.8,
            "bidfloorcur": "GBP"
            }]
}
```
Here's is entire curl request with headers, ua and other:
```
curl --location 'http://localhost:8000/openrtb2/auction' \
--header 'Content-Type: application/json' \
--header 'X-Forwarded-For: 103.81.64.0' \
--header 'Cookie: cookieRegion=nva; instUid=0446c3a6-c114-4b53-898c-008d62aad8c5; uids=eyJ0ZW1wVUlEcyI6eyJvcGVueCI6eyJ1aWQiOiIxMTExMSIsImV4cGlyZXMiOiIyMDI0LTA2LTI0VDE1OjU4OjU1Ljg4MDI5OSswNTozMCJ9fX0=' \
--data '{
    "ext": {
        "prebid": {
            "debug": true
        },
        "insticator": {
            "adapter": {
                "vendor": "prebid",
                "prebid": "8.38.0"
            }
        }
    },
    "test": 1,
    "site": {
        "ref": "",
        "domain": "cheeseheadtv.com",
        "page": "https://cheeseheadtv.com/v2.1.147/lol/in-game",
        "keywords": "helo,hry",
        "content": {
            "cat": ["IAB1-1"],
            "genre": "hello"
        },
        "mobile": 1
    },
    "tmax": 7000,
    "regs": {
        "ext": {
            "gdpr": 1        
        }
    },
    "id": "143166a46498cf89",
    "source": {
        "fd": 1
    },
    "device": {
        "sua": {
            "source": 1,
            "platform": {
                "brand": "macOS"
            },
            "browsers": [
                {
                    "brand": "Google Chrome",
                    "version": [
                        "123"
                    ]
                },
                {
                    "brand": "Not:A-Brand",
                    "version": [
                        "8"
                    ]
                },
                {
                    "brand": "Chromium",
                    "version": [
                        "123"
                    ]
                }
            ],
            "mobile": 0
            },
        "ext": {},
        "os": "Windows",
        "h": 1080,
        "ppi": 45,
        "language": "ja",
        "dnt": 0,
        "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.5845.190 Safari/537.36",
        "devicetype": 2,
        "carrier": "So-net",
        "osv": "10",
        "w": 1920,
        "model": "Chrome",
        "connectiontype": 0,
        "make": "Google"
        
        
        
    },
    "user": {
        "ext": {
            "eids": [
                {
                    "uids": [
                        {
                            "ext": {
                                "linktype": "2",
                                "pba": "4Gmzuev8uOCkWlYYGEz/7w=="
                            },
                            "atype": 1,
                            "id": "ID5*HE49hy4-v4Pgoe3QSmegEWz6CZV5_v7h_wv1LdRmVT6OF_Vwj1Y5n-gNCHSerhMN"
                        }
                    ],
                    "source": "id5-sync.com"
                },
                {
                    "uids": [
                        {
                            "atype": 1,
                            "id": "0609ljdllbbgihjh7k7g977h6b9akea9gd760wk00ggqusws2y2q622s0g6eyme6q"
                        }
                    ],
                    "source": "audigent.com"
                },
                {
                    "uids": [
                        {
                            "atype": 1,
                            "id": "3fe32eea-612f-41e5-ab35-c85b453cfa7e"
                        }
                    ],
                    "source": "pubcid.org"
                }
            ],
            "consent": "asdasdasd"
        },
        "id": "fc1845bb-c4f1-4064-98b2-7a0aa7acdf20",
        "keywords": "action,sci-fi"
    },
    "imp": [
        {
            "ext": {
                "gpid": "bostonhockeynow.com-div-insticator [...]

2024-07-03 11:19 UTC, shubhamc-ins commented
Here's is BidRequest received at the exchange in the ORTB controller:
```
{
  id: "143166a46498cf89",
  imp: [
    {
      id: "8068037539d483f7",
      banner: {
        format: [
          {
            w: 300,
            h: 250,
          },
        ],
      },
      tagid: "div-insticator-ad-1",
      bidfloor: 1.0127,
      bidfloorcur: "USD",
      secure: 1,
      ext: {
        insticator: {
          adUnitId: "01EX2DK7MW4BNN8TS2R0AT576D",
        },
      },
    },
  ],
  site: {
    domain: "cheeseheadtv.com",
    page: "https://cheeseheadtv.com/v2.1.147/lol/in-game",
    mobile: 1,
    publisher: {
      domain: "cheeseheadtv.com",
    },
    content: {
      genre: "hello",
      cat: [
        "IAB1-1",
      ],
    },
    keywords: "helo,hry",
    ext: {
      amp: 0,
    },
  },
  device: {
    dnt: 0,
    ua: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.5845.190 Safari/537.36",
    sua: {
      browsers: [
        {
          brand: "Google Chrome",
          version: [
            "123",
          ],
        },
        {
          brand: "Not:A-Brand",
          version: [
            "8",
          ],
        },
        {
          brand: "Chromium",
          version: [
            "123",
          ],
        },
      ],
      platform: {
        brand: "macOS",
      },
      mobile: 0,
      source: 1,
    },
    ip: "103.81.64.0",
    devicetype: 2,
    make: "Google",
    model: "Chrome",
    os: "Windows",
    osv: "10",
    h: 1080,
    w: 1920,
    ppi: 45,
    language: "ja",
    carrier: "So-net",
    connectiontype: 0,
    ext: {
    },
  },
  user: {
    keywords: "action,sci-fi",
    ext: {
      consent: "asdasdasd",
    },
  },
  test: 1,
  at: 1,
  tmax: 7000,
  source: {
    fd: 1,
    tid: "998ff0bf-8eef-4aa6-9216-d4c07a9cd485",
  },
  regs: {
    ext: {
      gdpr: 1,
    },
  },
  ext: {
    insticator: {
      caller: [
        {
          name: "Prebid-Server",
          version: "n/a",
        },
      ],
    },
  },
}
```

2024-07-03 11:21 UTC, shubhamc-ins commented
Here is the final response of the prebid-server of the same request. Note, I have debug mode enabled in the prebid-server. Therefore, the response has a debug field which determines the steps it went through.

```
{
    "id": "143166a46498cf89",
    "seatbid": [
        {
            "bid": [
                {
                    "id": "02b7152e-392e-11ef-a16d-6e93cff0f2aa",
                    "impid": "8068037539d483f7",
                    "price": 4.5,
                    "adm": "<a target=\"_blank\" href=\"\"><img src=\"https://d1lzbb0kfd0kc4.cloudfront.net/Include CTA - Desktop Engage - Desktop - 300x250.png\" border=\"0\" /></a><div style=\"position:absolute;left:0;top:0;visibility:hidden;\"><img src=\"http://localhost:7000/v1/win?did=aW5zdGljYXRvcg%3D%3D&bid=MDFKMVc1MlpIR1YzOUQ3UFNLRjNaVFQyM0o%3D&price=4.5\" /></div>",
                    "cid": "insticator_291847",
                    "crid": "insticator_415665",
                    "w": 300,
                    "h": 350,
                    "exp": 59,
                    "ext": {
                        "origbidcpm": 4.5,
                        "origbidcur": "USD",
                        "prebid": {
                            "meta": {
                                "adaptercode": "insticator"
                            },
                            "type": "banner"
                        }
                    }
                }
            ],
            "seat": "insticator"
        }
    ],
    "cur": "USD",
    "ext": {
        "debug": {
            "httpcalls": {
                "insticator": [
                    {
                        "uri": "http://localhost:7000/v1/prebidserver?debug=true",
                        "requestbody": "{\"id\":\"143166a46498cf89\",\"imp\":[{\"id\":\"8068037539d483f7\",\"banner\":{\"format\":[{\"w\":300,\"h\":250}]},\"tagid\":\"div-insticator-ad-1\",\"bidfloor\":1.0127,\"bidfloorcur\":\"USD\",\"secure\":1,\"ext\":{\"insticator\":{\"adUnitId\":\"01EX2DK7MW4BNN8TS2R0AT576D\"}}}],\"site\":{\"domain\":\"cheeseheadtv.com\",\"page\":\"https://cheeseheadtv.com/v2.1.147/lol/in-game\",\"mobile\":1,\"publisher\":{\"domain\":\"cheeseheadtv.com\"},\"content\":{\"genre\":\"hello\",\"cat\":[\"IAB1-1\"]},\"keywords\":\"helo,hry\",\"ext\":{\"amp\":0}},\"device\":{\"dnt\":0,\"ua\":\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.5845.190 Safari/537.36\",\"sua\":{\"browsers\":[{\"brand\":\"Google Chrome\",\"version\":[\"123\"]},{\"brand\":\"Not:A-Brand\",\"version\":[\"8\"]},{\"brand\":\"Chromium\",\"version\":[\"123\"]}],\"platform\":{\"brand\":\"macOS\"},\"mobile\":0,\"source\":1},\"ip\":\"103.81.64.0\",\"devicetype\":2,\"make\":\"Google\",\"model\":\"Chrome\",\"os\":\"Windows\",\"osv\":\"10\",\"h\":1080,\"w\":1920,\"ppi\":45,\"language\":\"ja\",\"carrier\":\"So-net\",\"connectiontype\":0,\"ext\":{}},\"user\":{\"keywords\":\"action,sci-fi\",\"ext\":{\"consent\":\"asdasdasd\"}},\"test\":1,\"at\":1,\"tmax\":7000,\"source\":{\"fd\":1,\"tid\":\"1d95844a-900b-48e9-8eea-85d26d1b337e\"},\"regs\":{\"ext\":{\"gdpr\":1}},\"ext\":{\"insticator\":{\"caller\":[{\"name\":\"Prebid-Server\",\"version\":\"n/a\"}]}}}",
                        "requestheaders": {
                            "Content-Type": [
                                "application/json;charset=utf-8"
                            ],
                            "X-Prebid": [
                                "pbs-go/unknown"
                            ]
                        },
                        "responsebody": "{\"id\":\"143166a46498cf89\",\"seatbid\":[{\"bid\":[{\"id\":\"02b7152e-392e-11ef-a16d-6e93cff0f2aa\",\"impid\":\"8068037539d483f7\",\"price\":4.5,\"adm\":\"<a target=\\\"_blank\\\" href=\\\"\\\"><img src=\\\"https://d1lzbb0kfd0kc4.cloudfront.net/Include CTA - Desktop Engage - Desktop - 300x250.png\\\" border=\\\"0\\\" /></a><div style=\\\"position:absolute;left:0;top:0;visibility:hidden;\\\"><img src=\\\"http://localhost:7000/v1/win?did=aW5zdGljYXRvcg%3D%3D&bid=MDFKMVc1MlpIR1YzOUQ3UFNLRjNaVFQyM0o%3D&price=4.5\\\" /></div>\",\"cid\":\"insticator_291847\",\"crid\":\"insticator_415665\",\"w\":300,\"h\":350,\"exp\":59,\"ext\":{}}],\"seat\":\"insticator_insticator_8980\"}],\"bidid\":\"01J1W52ZHFSKZK460XTVGXKWVA\",\"debug\":{\"0\":{\"message\":\"DebugContextBuilder: init\",\"tookMs\":0.01925},\"1\":{\"message\":\"AdUnitEnricher: ad units found\",\"tookMs\":3376.033127,\"data\":{\"adUnits\":[\"01EX2DK7MW4BNN8TS2R0AT576D\"],\"impressions\":[\"8068037539d483f7\"]}},\"2\":{\"message\":\"SourceEnricher: source object was updated\",\"tookMs\":4.875415999999859,\"data\":{\"schain\":{\"ver\":\"1.0\",\"nodes\":[{\"asi\":\"insticator.com\",\"sid\":\"insticator\",\"rid\":\"143166a46498cf89\",\"hp\":1}],\"complete\":1}}},\"3\":{\"message\":\"SiteEnricher: site info added\",\"tookMs\":3377.280961,\"data\":{\"site\":{\"domain\":\"cheeseheadtv.com\",\"page\":\"https://cheeseheadtv.com/v2.1.147/lol/in-game\",\"mobile\":1,\"publisher\":{\"domain\":null,\"id\":\"insticator\",\"name\":\"Insticator\"},\"content\":{\"genre\":\"hello\",\"cat\":[\"IAB1-1\"],\"keywords\":\"helo,hry\"},\"keywords\":\"helo,hry\",\"ext\":{\"amp\":0},\"privacypolicy\":0}}},\"4\":{\"message\":\"AppEnricher: app info added\",\"tookMs\":5.035832000000028,\"data\":{\"app\":null}},\"5\":{\"message\":\"DeviceEnricher: device info added\",\"tookMs\":3382.35092,\"data\":{\"device\":{\"dnt\":0,\"ua\":\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.5845.190 Safari/537.36\",\"sua\":{\"browsers\":[{\"brand\":\"Google Chrome\",\"version\":[\"123\"]},{\"brand\":\"Not:A-Brand\",\"version\":[\"8\"]},{\"brand\":\"Chromium\",\"version\":[\"123\"]}],\"platform\":{\"brand\":\"macOS\"},\"mobile\":0,\"source\":1},\"devicetype\":2,\"make\":\"Google\",\"model\":\"Chrome\",\"os\":\"Windows\",\"osv\":\"10\",\"h\":1080,\"w\":1920,\"ppi\":45,\"language\":\"ja\",\"carrier\":\"So-net\",\"connectiontype\":0,\"ext\":{},\"lmt\":0,\"geo\":{\"lat\":-5.4291,\"lon\":105.2615,\"accuracy\":1000,\"country\":\"IDN\",\"region\":\"LA\",\"type\":2,\"ipservice\":3,\"utcoffset\":-420},\"ip\":\"103.81.64.0\"}}},\"6\":{\"message\":\"IFAEnricher: IFA code added\",\"tookMs\":5.2777900000000955,\"data\":{\"ifa\":null}},\"7\":{\"message\":\"PrivacyPolicyEnricher: privacy policy updated\",\"tookMs\":3382.41017,\"data\":{\"site\":{\"domain\":\"cheeseheadtv.com\",\"page\":\"https://cheeseheadtv.com/v2.1.147/lol/in-game\",\"mobile\":1,\"publisher\":{\"domain\":null,\"id\":\"insticator\",\"name\":\"Insticator\"},\"content\":{\"genre\":\"hello\",\"cat\":[\"IAB1-1\"],\"keywords\":\"helo,hry\"},\"keywords\":\"helo,hry\",\"ext\":{\"amp\":0},\"privacypolicy\":0}}},\"8\":{\"message\":\"Allowlist: filter publisher domains\",\"tookMs\":5.430539999999837,\"data\":{\"validAdUnitIds\":[\"01EX2DK7MW4BNN8TS2R0AT576D\"]}},\"9\":{\"message\":\"EventBuilder: initial info added\",\"tookMs\":3383.0028780000002},\"10\":{\"message\":\"Exchange: cookie matching retrieved\",\"tookMs\":8.768456999999671,\"data\":{\"syncData\":null}},\"11\":{\"message\":\"Exchange: bid responses\",\"tookMs\":3692.701253,\"data\":{\"bidTaskResults\":[{\"id\":\"01J1W52YZATZ9NK5MKMWV1BCRX\",\"bidRequest\":{\"id\":\"insticator_143166a46498cf89_1\",\"imp\":[{\"id\":\"01J1W52YNRS1T3VYMFHYQWTCW9\",\"bidfloor\":1.1252222222222221,\"bidfloorcur\":\"USD\",\"secure\":1,\"ext\":{\"insticator\":{\"adUnitId\":\"01EX2DK7MW4BNN8TS2R0AT576D\"},\"ttx\":{\"zoneid\":\"dukr5O4SWr6iygaKkGJozW\"}},\"banner\":{\"format\":[{\"w\":300,\"h\":250},{\"w\":300,\"h\":50},{\"w\":300,\"h\":100},{\"w\":250,\"h\":250},{\"w\":250,\"h\":50},{\"w\":200,\"h\":200},{\"w\":180,\"h\":150},{\"w\":160,\"h\":90},{\"w\":336,\"h\":280},{\"w\":320,\"h\":50},{\"w\":320,\"h\":100}],\"w\":300,\"h\":250,\"expdir\":[1,2,3,4]},\"originalimpid\":\"01J1W52YNP3QH7YM1QXX3TN4SS\"}],\"site\":{\"domain\":\"cheeseheadtv.com\",\"page\":\"https://cheeseheadtv.com/v2.1.147/lol/in-game\",\"mobile\":1,\"publishe [...]

2024-07-03 14:41 UTC, shubhamc-ins commented
Here's request PBjs is sending to prebid-server:
```
{
  "id": "139fc2ce857bbb",
  "tmax": 3000,
  "source": {
    "fd": 1
  },
  "site": {
    "domain": "localhost:8081",
    "page": "http://localhost:8081/pbs/banner?pbjs_debug=true",
    "ref": null
  },
  "device": {
    "w": 970,
    "h": 1258,
    "js": 1,
    "ext": {
      "localStorage": false,
      "cookies": false
    },
    "dnt": 0,
    "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0",
    "language": "en",
    "sua": {
      "source": 1,
      "platform": {
        "brand": "macOS"
      },
      "browsers": [
        {
          "brand": "Not/A)Brand",
          "version": [
            "8"
          ]
        },
        {
          "brand": "Chromium",
          "version": [
            "126"
          ]
        },
        {
          "brand": "Microsoft Edge",
          "version": [
            "126"
          ]
        }
      ],
      "mobile": 0
    }
  },
  "regs": {
    "ext": {
      "gppSid": []
    },
    "coppa": 0
  },
  "user": {
    "id": "76d12c78-f795-43dd-87a3-5209144ac2e2"
  },
  "imp": [
    {
      "id": "2be41568563ff9",
      "tagid": "div-insticator-ad-1",
      "secure": 0,
      "ext": {
        "insticator": {
          "adUnitId": "01EX2DK7MW4BNN8TS2R0AT576D"
        },
        "prebid": {
          "debug": true,
          "bidder": {
            "insticator": {
              "adUnitId": "01EX2DK7MW4BNN8TS2R0AT576D"
            }
          }
        }
      },
      "banner": {
        "format": [
          {
            "w": 336,
            "h": 280
          },
          {
            "w": 300,
            "h": 250
          },
          {
            "w": 320,
            "h": 100
          }
        ]
      }
    }
  ],
  "ext": {
    "insticator": {
      "adapter": {
        "vendor": "prebid",
        "prebid": "9.2.0-pre"
      },
      "sspTest": 1
    }
  }
}```

2024-07-09 19:43 UTC, merged